<a href="https://colab.research.google.com/github/randomcuboid06/ML-CD-Lab/blob/main/FMLT_Week_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TS Weather data December 2022.csv')
df
df.columns

Index(['District', 'Mandal', 'Date', 'Rain (mm)', 'Min Temp (°C)',
       'Max Temp (°C)', 'Min Humidity (%)', 'Max Humidity (%)',
       'Min Wind Speed (Kmph)', 'Max Wind Speed (Kmph)'],
      dtype='object')

In [ ]:
hyd_df = df.loc[df['District'] == 'Hyderabad']
hyd_df

,District,Mandal,Date,Rain (mm),Min Temp (°C),Max Temp (°C),Min Humidity (%),Max Humidity (%),Min Wind Speed (Kmph),Max Wind Speed (Kmph)
1705,Hyderabad,Amberpet,01-Dec-22,0.0,19.0,30.1,28.9,78.0,0.0,2.2
1706,Hyderabad,Amberpet,02-Dec-22,0.0,21.1,29.9,43.5,84.1,0.0,0.9
1707,Hyderabad,Amberpet,03-Dec-22,0.0,21.9,30.2,52.4,95.1,0.0,33.5
1708,Hyderabad,Amberpet,04-Dec-22,0.0,21.7,30.2,51.9,96.5,0.0,33.7
1709,Hyderabad,Amberpet,05-Dec-22,0.0,20.3,30.9,50.0,89.4,0.0,33.2
...,...,...,...,...,...,...,...,...,...,...
2196,Hyderabad,Tirumalgiri,27-Dec-22,0.0,19.6,28.1,66.5,94.1,0.0,5.5
2197,Hyderabad,Tirumalgiri,28-Dec-22,0.0,20.2,30.9,60.2,94.1,0.0,4.6
2198,Hyderabad,Tirumalgiri,29-Dec-22,0.0,20.3,32.8,51.0,90.8,0.0,7.3
2199,Hyderabad,Tirumalgiri,30-Dec-22,0.0,20.4,32.3,51.6,88.4,0.0,3.0
2200,Hyderabad,Tirumalgiri,31-Dec-22,0.0,19.9,31.7,53.6,85.9,0.0,5.9

# Measures of central tendency

- mean

In [ ]:
hyd_df.Mandal.unique()

array(['Amberpet', 'Ameerpet', 'Asifnagar', 'Bahadurpura', 'Bandlaguda',
       'Charminar', 'Golkonda', 'Himayatnagar', 'Khairatabad',
       'Maredpally', 'Musheerabad', 'Nampally', 'Saidabad',
       'Secunderabad', 'Shaikpet', 'Tirumalgiri'], dtype=object)

In [ ]:
home = hyd_df.loc[df['Mandal']=='Maredpally']

In [ ]:
home.mean()

<ipython-input-41-00abb57fd077>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  home.mean()

Rain (mm)                 0.358065
Min Temp (°C)            16.954839
Max Temp (°C)            30.116129
Min Humidity (%)         41.693548
Max Humidity (%)         90.309677
Min Wind Speed (Kmph)     0.000000
Max Wind Speed (Kmph)    13.403226
dtype: float64

- median

In [ ]:
home.median()

<ipython-input-42-72f05c1695fe>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  home.median()

Rain (mm)                  0.0
Min Temp (°C)             17.5
Max Temp (°C)             30.6
Min Humidity (%)          38.8
Max Humidity (%)         100.0
Min Wind Speed (Kmph)      0.0
Max Wind Speed (Kmph)      8.1
dtype: float64

- mode

In [ ]:
home.mode()

,District,Mandal,Date,Rain (mm),Min Temp (°C),Max Temp (°C),Min Humidity (%),Max Humidity (%),Min Wind Speed (Kmph),Max Wind Speed (Kmph)
0,Hyderabad,Maredpally,01-Dec-22,0.0,15.0,30.0,18.8,100.0,0.0,6.0
1,NaN,NaN,02-Dec-22,NaN,NaN,31.1,19.0,NaN,NaN,8.6
2,NaN,NaN,03-Dec-22,NaN,NaN,31.2,21.0,NaN,NaN,NaN
3,NaN,NaN,04-Dec-22,NaN,NaN,31.4,21.2,NaN,NaN,NaN
4,NaN,NaN,05-Dec-22,NaN,NaN,32.2,25.7,NaN,NaN,NaN
5,NaN,NaN,06-Dec-22,NaN,NaN,NaN,26.4,NaN,NaN,NaN
6,NaN,NaN,07-Dec-22,NaN,NaN,NaN,28.1,NaN,NaN,NaN
7,NaN,NaN,08-Dec-22,NaN,NaN,NaN,29.7,NaN,NaN,NaN
8,NaN,NaN,09-Dec-22,NaN,NaN,NaN,30.0,NaN,NaN,NaN
9,NaN,NaN,10-Dec-22,NaN,NaN,NaN,31.1,NaN,NaN,NaN
10,NaN,NaN,11-Dec-22,NaN,NaN,NaN,32.9,NaN,NaN,NaN
11,NaN,NaN,12-Dec-22,NaN,NaN,NaN,33.7,NaN,NaN,NaN
12,NaN,NaN,13-Dec-22,NaN,NaN,NaN,34.3,NaN,NaN,NaN
13,NaN,NaN,14-Dec-22,NaN,NaN,NaN,35.0,NaN,NaN,NaN
14,NaN,NaN,15-Dec-22,NaN,NaN,NaN,37.5,NaN,NaN,NaN
15,NaN,NaN,16-Dec-22,NaN,NaN,NaN,38.8,NaN,NaN,NaN
16,NaN,NaN,17-Dec-22,NaN,NaN,NaN,40.9,NaN,NaN,NaN
17,NaN,NaN,18-Dec-22,NaN,NaN,NaN,41.4,NaN,NaN,NaN
18,NaN,NaN,19-Dec-22,NaN,NaN,NaN,44.5,NaN,NaN,NaN
19,NaN,NaN,20-Dec-22,NaN,NaN,NaN,47.1,NaN,NaN,NaN
20,NaN,NaN,21-Dec-22,NaN,NaN,NaN,49.7,NaN,NaN,NaN
21,NaN,NaN,22-Dec-22,NaN,NaN,NaN,50.1,NaN,NaN,NaN
22,NaN,NaN,23-Dec-22,NaN,NaN,NaN,52.3,NaN,NaN,NaN
23,NaN,NaN,24-Dec-22,NaN,NaN,NaN,53.3,NaN,NaN,NaN
24,NaN,NaN,25-Dec-22,NaN,NaN,NaN,53.7,NaN,NaN,NaN
25,NaN,NaN,26-Dec-22,NaN,NaN,NaN,55.2,NaN,NaN,NaN
26,NaN,NaN,27-Dec-22,NaN,NaN,NaN,57.6,NaN,NaN,NaN
27,NaN,NaN,28-Dec-22,NaN,NaN,NaN,59.5,NaN,NaN,NaN
28,NaN,NaN,29-Dec-22,NaN,NaN,NaN,68.9,NaN,NaN,NaN
29,NaN,NaN,30-Dec-22,NaN,NaN,NaN,74.5,NaN,NaN,NaN
30,NaN,NaN,31-Dec-22,NaN,NaN,NaN,80.6,NaN,NaN,NaN

# Measures of data spread

In [ ]:
import numpy as np

- quartiles

In [ ]:
quartiles = np.quantile(df['Max Temp (°C)'], [0, 0.25, 0.5, 0.75, 1])

- inter-quartile range

In [ ]:
print(quartiles[3] - quartiles[1])

# or

from scipy.stats import iqr

print(iqr(df['Max Temp (°C)']))

2.3999999999999986
2.3999999999999986

In [ ]:
df.describe()

,Rain (mm),Min Temp (°C),Max Temp (°C),Min Humidity (%),Max Humidity (%),Min Wind Speed (Kmph),Max Wind Speed (Kmph)
count,18414.000000,18414.00000,18414.000000,18414.000000,18414.000000,18414.000000,18414.000000
mean,0.225964,17.61148,31.479630,44.829619,95.256099,0.016411,7.135685
std,1.500799,2.92449,2.068093,13.397496,7.409757,0.194828,6.343540
min,0.000000,5.90000,21.500000,7.400000,48.800000,0.000000,0.000000
25%,0.000000,15.40000,30.400000,34.900000,93.600000,0.000000,4.200000
50%,0.000000,18.10000,31.900000,44.300000,98.700000,0.000000,6.400000
75%,0.000000,19.90000,32.800000,53.700000,100.000000,0.000000,8.900000
max,52.200000,25.10000,37.300000,99.700000,100.000000,9.100000,66.400000

- standard deviation

In [ ]:
hyd_df['Max Temp (°C)'].std()

2.0971329868223374

- variance

In [ ]:
hyd_df['Max Temp (°C)'].var()

4.397966764418378